addEventListener: ADICIONA UM EVENTO A UM ELEMENTO ESPECÍFICO

style: SERVE PARA MODIFICAR O CSS DE UM ELEMENTO

SRC: SERVE PARA MODIFICA O ENDEREÇO COMO IMAGEM

str.replace: Retorne uma string onde "Microsoft" é substituído por "W3Schools": ESSA FUNÇÃO SERVE PARA SUBSTITUIR
STRINGS

ONLOAD: FUNÇÃO QUE É EXECUTADA LOGO AO CARREGAR A PÁGINA

ONCLICK: FUNÇÃO QUE É EXECUTADO LOGO AO CLICAR

ONMOUOVER: QUANDO PASSAR O MOUSE POR CIMA

OKEYPRESS: QUANDO PRECIONAR A TECLA

ONKEYCODE: MOSTRA O CÓDIGO DA TECLA

window.onscroll = function(): FAZ ALGUMA COISA QUANDO VOCÊ DÁ O SCROLL NA TELA

//https://developer.mozilla.org/pt-BR/docs/Web/API/Window/scroll